name: run daily

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  schedule:
    - cron: '0 8 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed

      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v3

      - run: |
          python -m venv venv
          pip install -r requirements.txt
          source venv/bin/activate
      - name: execute script
        run: python src/main.py ${{ secrets.PROXY }}
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated price" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.RUN_TOK }}
          branch: main