name: Run Daily

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  schedule:
    - cron: '0 8 * * *' 
  workflow_dispatch:

jobs:
  build:
  runs-on: self-hosted
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3

      - name: execute script
        run: python3 src/main.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated price" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.RUN_TOK }}
          branch: main
